### PR TITLE
Merge of contamination branch and updates to rRNA 

### PR DESCRIPTION
**Pull request by alexiswl**

### CODE REVIEW

**Comment by andrei-seleznev** [comment]
little problem here on line 120 in mapping_metrics, this barfs on dragen 3.9 output because it uses "rRNA filtered reads" instead of rrna_filtered_reads_key
I can fix this up by setting the var earlier, moving the block at 131 to 113. does that make sense to you?

**Comment by alexiswl** [comment]
> I can fix this up by setting the var earlier, moving the block at 131 to 113. does that make sense to you?

Logically that makes the most sense, now I'm confused on how this worked before the rebase.

**Comment by andrei-seleznev** [comment]
that didn't work either. using the first file from dragen issue 32 to test, got:
_│   File "/home/aseleznev/dev/multiqc/Multiqc-MyFork/MultiQC/venv/lib/python3.8/site-packages/multiqc/plots/bargraph.py", line 104, in plot                               │
│     if type(cats[0]) is str or type(cats[0]) is unicode:                                                                                                                │
│ IndexError: list index out of range_            
...i'll diff this PR code with your fork's code in branch rrna-fix and take a look

**Comment by andrei-seleznev** [comment]
looks good thanks Alexis

**Pull request merged**
